# Generated by Django 5.1.6 on 2025-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='interestrate',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loanamount',
            field=models.BigIntegerField(default=30000),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loantype',
            field=models.CharField(default='Personal Loan', max_length=20),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='reasonforloan',
            field=models.CharField(default='Not Specified', max_length=500),
        ),
    ]
