# Generated by Django 5.1.7 on 2025-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_loanaccount_interestrate_loanaccount_loanamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccount',
            old_name='loanamount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='interestrate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='loantype',
            new_name='loan_type',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='reasonforloan',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='email',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
